apiVersion: v1
kind: ConfigMap
metadata:
  name: azkaban-users-configmap
  namespace: default
data:
  content: |-
    <azkaban-users>
      <user groups="azkaban" password="azkaban" roles="admin" username="azkaban"/>
      <user password="metrics" roles="metrics" username="metrics"/>
    
      <role name="admin" permissions="ADMIN"/>
      <role name="metrics" permissions="METRICS"/>
    </azkaban-users>
