apiVersion: v1
kind: ConfigMap
metadata:
  name: azkaban-users-configmap
  namespace: default
data:
  content: |-
    <azkaban-users>
      <role name="admin" permissions="ADMIN" / >
      <group name="admins" roles="admin" / >
      <user username="azkaban" password="secret"  groups="admins" / >
    </azkaban-users>
